### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by scotow** [conix-center/LightAnchors#1]
Hi, thanks for the app.

I tried to run your app to decode LightAnchors signals emitted by a led and by running their demo code available on the official website (https://www.lightanchors.org/demo-starter-code), no DAC (PWN) on a Arduino One, but nothing is showing.

I noticed some circles too, what are they made for?

Regards.

**Comment by adwaitnd** [comment]
I believe you're referring to a different project having the same name. We work closely with the other research group but our App won't work for their light anchor encoding scheme.

**Comment by scotow** [comment]
Ok thank you for the information.
